Fix pip-tools / pip error on pip-compile
ImportError: cannot import name 'BAR_TYPES' from
'pip._internal.cli.progress_bars'

[noissue]

(cherry picked from commit ad3dc6a6be3d1f7028bf81e59d8f4cd55b3fc4c2)